notifications:
  email:
    recipients:
      - andili@kth.se
    on_success: always
    on_failure: always


language: c
dist: xenial
env: HOLBA_OPT_DIR=$HOME/cache

cache:
  directories:
    - $HOME/cache

jobs:
  include:
    - stage: "Prepare polyml & HOL4"
      before_script:
        - scripts/setup/install_poly.sh
        - scripts/setup/install_hol4.sh
      script: true

    - stage: "Compile and test"
      script: . scripts/setup/env.sh && scripts/ci/compile.sh && scripts/ci/test.sh


